### ISSUE TITLE
主站7年未更新，无法起到介绍我校的作用

### ISSUE THREAD

**Issue by huangjj27** [sysu/sysu.github.com#3]
尤其是 微教务系统已经没有任何链接了

**Comment by ltaoist** [comment]
https://crlhd.xmu.edu.cn/2019/0712/c11914a373152/page.htm
\~\~ 随手扩散校委陈书记的采访  \~\~

个人觉得，工科仔有点不知道怎么说话，而且也没看到啥其他高校的先例 TvT

**Comment by ltaoist** [comment]
请转移到 https://github.com/sysu/sysu.github.io/issues/1
